# Generated by Django 4.2.7 on 2023-12-27 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="level",
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_earning",
                    models.IntegerField(default=0, verbose_name="Total Earning"),
                ),
                (
                    "total_withdrawal",
                    models.IntegerField(default=0, verbose_name="Total Withdrawal"),
                ),
                (
                    "total_referral",
                    models.IntegerField(default=0, verbose_name="Total Referral"),
                ),
                (
                    "total_referral_earning",
                    models.IntegerField(
                        default=0, verbose_name="Total Referral Earning"
                    ),
                ),
                (
                    "total_referral_withdrawal",
                    models.IntegerField(
                        default=0, verbose_name="Total Referral Withdrawal"
                    ),
                ),
                (
                    "total_referral_balance",
                    models.IntegerField(
                        default=0, verbose_name="Total Referral Balance"
                    ),
                ),
                (
                    "related_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Stats",
            },
        ),
    ]
